version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/code
      - ./file:/file
    ports:
      - "3000:3000"
  db:
    image: postgres:10-alpine
    # restart: always
    volumes:
      - ./postgres_data_prod:/var/lib/postgresql/data/
      # copy the sql script to create tables
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
      # copy the sql script to fill tables
      - ./sql/fill.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    env_file:
      - ./.env.db
    ports:
      - "5434:5434"